name: patofy
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



dependency_overrides:
  args: ^2.4.2


dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  charts_flutter: ^0.12.0
  pie_chart: ^5.3.2
  flutterfire_cli: ^0.2.6
  path_provider_android: ^2.0.27
  path_provider: ^2.0.15
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  firebase_core: ^2.15.0
  intl_phone_number_input: ^0.7.3+1
  pdf: ^3.10.4
  excel: ^2.1.0
  permission_handler: ^10.4.3
  share: ^2.0.4
  open_file: ^3.3.2
  url_launcher: ^6.1.12
  syncfusion_flutter_pdf: ^21.2.4
  csv: ^5.0.2
  google_sign_in: ^6.1.4
  googleapis: ^11.3.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"







  flutter_lints: ^2.0.2


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/icon.png
    - assets/icons/bg.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
