// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCb_Kzfhr2QYr9SHRD8iDYiI-LtiCRzWMc',
//     appId: '1:13960624684:web:da5246866fa893e2962f89',
//     messagingSenderId: '13960624684',
//     projectId: 'patofy-db',
//     authDomain: 'patofy-db.firebaseapp.com',
//     storageBucket: 'patofy-db.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBP4sro23NJ3dAPLxvTG2kVVxjp1KSbuGc',
//     appId: '1:13960624684:android:5bf99f6a420570ba962f89',
//     messagingSenderId: '13960624684',
//     projectId: 'patofy-db',
//     storageBucket: 'patofy-db.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB1lWPGrlO24aljILKC1DQrDz3YCW3HIPM',
//     appId: '1:13960624684:ios:d842bd74e24e6f0a962f89',
//     messagingSenderId: '13960624684',
//     projectId: 'patofy-db',
//     storageBucket: 'patofy-db.appspot.com',
//     iosClientId: '13960624684-dmaiov72l4aibalh53e8n3jei2bi4ori.apps.googleusercontent.com',
//     iosBundleId: 'com.example.patofy',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB1lWPGrlO24aljILKC1DQrDz3YCW3HIPM',
//     appId: '1:13960624684:ios:0ce39ae8f3e04f6e962f89',
//     messagingSenderId: '13960624684',
//     projectId: 'patofy-db',
//     storageBucket: 'patofy-db.appspot.com',
//     iosClientId: '13960624684-nfh4rvdfkjd9e2k6uk7u42e7t9k5kdvp.apps.googleusercontent.com',
//     iosBundleId: 'com.example.patofy.RunnerTests',
//   );
// }
